---
apiVersion: v1
kind: Secret
metadata:
  name: authelia-secrets
  namespace: authelia
type: Opaque
stringData:
  session.encryption.key: 9r2qLAXF7ZhBx7VIElaDMyduq/4XnJhTyoD8CL9Q2JE=
  storage.encryption.key: 9r2qLAXF7ZhBx7VIElaDMyduq/4XnJhTyoD8CL9Q2JE=
