---
pod:
  kind: Deployment

configMap:
  server:
    port: 9091

  log:
    level: info

  theme: auto

  authentication_backend:
    file:
      enabled: true
      path: /config/users_database.yml

  access_control:
    default_policy: deny
    rules:
      - domain:
          - auth.k8s.wlankabel.ch
        policy: bypass

  session:
    cookies:
      - domain: k8s.wlankabel.ch
        subdomain: auth
    encryption_key:
      secret_name: authelia-secrets
      path: session.encryption.key

  storage:
    local:
      enabled: true
      path: /config/db.sqlite3
    encryption_key:
      secret_name: authelia-secrets
      path: storage.encryption.key

  notifier:
    filesystem:
      enabled: true
      filename: /config/notification.txt

secret:
  existingSecret: authelia-secrets
  additionalSecrets:
    authelia-secrets:
      path: authelia-secrets

persistence:
  enabled: true
  storageClass: lh-ssd-r4
  accessModes:
    - ReadWriteOnce
  size: 1Gi

ingress:
  enabled: true
  className: cilium
  certManager: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: cilium
    ingress.cilium.io/tls-termination: "true"
    ingress.cilium.io/backend-protocol: HTTP
  tls:
    enabled: true
    secret: authelia-tls
