---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://dl.gitea.com/charts/'
      chart: gitea
      targetRevision: 12.1.0
      helm:
        values: |
          global:
            storageClass: lh-ssd-r3
          ingress:
            enabled: true
            className: cilium
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-staging"
            hosts:
              - host: git.k8s.wlankabel.ch
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - secretName: git-tls
                hosts:
                  - git.k8s.wlankabel.ch
          postgresql-ha:
            enabled: false
          postgresql:
            enabled: false
          gitea:
            config:
              database:
                DB_TYPE: sqlite3
                PATH: /data/gitea/gitea.db
          redis-cluster:
            enabled: false
          redis:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: s-gitea
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
