---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: v1.17.2
      helm:
        parameters:
          - name: crds.enabled
            value: "true"
    - repoURL: 'https://github.com/Cloud-native-engineering/sem04_k8s.git'
      path: 'cert-manager'
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
